### 1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [25]:
def divbyzero(a,b):
    try:
        e = a/b
    except Exception as e:
        return "getting error", e
    else:
        return e

In [26]:
divbyzero(10,5)

2.0

In [28]:
divbyzero(5,0)

('getting error', ZeroDivisionError('division by zero'))

### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [6]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+' '+j+' '+k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [31]:
import numpy as np

### 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [32]:
def vander_matrix(ip, n, increasing=False):
    
    if not increasing:
        return np.array([[x**(n-i-1) for i in range(n)] for x in ip]).reshape(len(ip),n)
    else:
        return np.array([[x**i for i in range(n)] for x in ip]).reshape(len(ip),n)
        
        
ip_vec = [1,2,3,4,5]
n = 4
print("Vander matrix with Decreasing order of powers\n")
print(vander_matrix(ip_vec,n))

Vander matrix with Decreasing order of powers

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [33]:
print("Vander matrix with Increasing order of powers\n")
print(vander_matrix(ip_vec,n,True))

Vander matrix with Increasing order of powers

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
